[package]
name = "chip8"
version = "1.0.0"
authors = ["Deokhwan Kim"]
description = "chip8 is a CHIP-8 interpreter written in Rust with Rust-SDL2."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dkim/chip8"
keywords = ["chip-8", "chip8"]
categories = ["emulators"]
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.11"
rand = "0.7.3"
sdl2 = "0.34.2"
snafu = { version = "0.6.8", features = ["backtraces"] }
spin_sleep = "1.0.0"
structopt = { version = "0.3.15", features = ["wrap_help"] }
strum = "0.18.0"
strum_macros = "0.18.0"

[features]
default = []
report_frame_rate = []
