[package]
name = "chip8"
version = "0.1.0"
authors = ["Deokhwan Kim"]
description = "chip8 is a CHIP-8 interpreter written in Rust."
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
snafu = { version = "0.6.2", features = ["backtraces"] }
structopt = { version = "0.3.11", features = ["wrap_help"] }
