[package]
name = "chip8"
version = "0.1.0"
authors = ["Deokhwan Kim"]
description = "chip8 is a CHIP-8 interpreter written in Rust with Rust-SDL2."
license = "MIT OR Apache-2.0"
readme = "README.md"
edition = "2018"

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
rand = "0.7.3"
sdl2 = "0.33.0"
snafu = { version = "0.6.2", features = ["backtraces"] }
spin_sleep = "0.3.7"
structopt = { version = "0.3.8", features = ["wrap_help"] }

[features]
default = []
report_frame_rate = []
