[package]
name = "chip8"
version = "0.1.0"
authors = ["Deokhwan Kim"]
description = "chip8 is a CHIP-8 interpreter written in Rust with Rust-SDL2."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/dkim/chip8"
keywords = ["chip-8", "chip8"]
categories = ["emulators"]
edition = "2018"

[badges]
appveyor = { repository = "dkim/chip8" }
travis-ci = { repository = "dkim/chip8" }

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
rand = "0.7.2"
sdl2 = "0.32.2"
snafu = { version = "0.6.0", features = ["backtraces"] }
spin_sleep = "0.3.7"
structopt = { version = "0.3.4", features = ["wrap_help"] }

[features]
default = []
report_frame_rate = []
