[licenses]
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-DFS-2016",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "bitflags", version = "1.2.1" },
    { name = "heck", version = "0.3.2" },
    { name = "hermit-abi", version = "0.1.19" },
    { name = "syn", version = "1.0.109" },
]
