[licenses]
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "MIT",
  "Unicode-3.0",
]

[bans]
multiple-versions = "deny"
skip = [
    { name = "bitflags", version = "1.2.1" },
    { name = "heck", version = "0.4.1" },
    { name = "windows-sys", version = "0.52.0" },
]
